USE test;
CREATE TABLE trajetos (
     id MEDIUMINT NOT NULL AUTO_INCREMENT,
     sigla VARCHAR(10) NOT NULL,
	 rota VARCHAR(100) NOT NULL,
	 partida_destino VARCHAR(100) NOT NULL,
	 trajeto_completo VARCHAR(1000) NOT NULL,
     PRIMARY KEY (id)
);

INSERT INTO trajetos (sigla, rota, partida_destino, trajeto_completo) VALUES
(
 '343','Campus Ipiranga','Terminal Borges De Medeiros/Terminal Campus Do Vale Ufrgs',
'Avenida Borges de Medeiros • 596 Avenida Julio De Castilhos • 500 Rua Sarmento Leite • 721 Avenida Joao Pessoa • 1371 Avenida João Pessoa • 145 Avenida Da Azenha • Avenida Ipiranga • 77 Rua São Luiz • 2485 DMAE Avenida Ipiranga • 2640 Avenida Ipiranga • Rua Santa Cecília • 3377 Avenida Ipiranga • 3835 Avenida Ipiranga • 4017 Avenida Ipiranga • 4745 Avenida Ipiranga • 5200 Avenida Ipiranga • Rua Doutor Salvador França • 6113 Avenida Ipiranga • 6311 Avenida Ipiranga • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • 1950 Rua Professor Cristiano Fischer • Avenida Ipiranga • 7029 Avenida Ipiranga • 8400 TORRE 7 Avenida Ipiranga • 927 Rua Padre Todesco • 6881 Avenida Bento Gonçalves • Beco Quatro • 7712 Avenida Bento Goncalves • Avenida Bento Gonçalves'
),
(
'353','Ipiranga PUC','Terminal Borges De Medeiros/Padre Todesco',
'Avenida Borges de Medeiros • 596 Avenida Julio De Castilhos • 580 Avenida Osvaldo Aranha • 914 Avenida Osvaldo Aranha • 753 Avenida José Bonifácio • Viaduto Tiradentes • 194 Rua Dona Eugenia • 2485 DMAE Avenida Ipiranga • 2640 Avenida Ipiranga • Rua Santa Cecília • 3377 Avenida Ipiranga • 3835 Avenida Ipiranga • 4017 Avenida Ipiranga • 4745 Avenida Ipiranga • 5200 Avenida Ipiranga • Rua Doutor Salvador França • 6113 Avenida Ipiranga • 6311 Avenida Ipiranga • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • 1950 Rua Professor Cristiano Fischer • Avenida Ipiranga • 402 Rua Albion • 276 Rua Albion • 135 Rua Osvaldo Pereira De Freitas • 175 Rua Osvaldo Pereira de Freitas • Rua Marcone • 500 Rua Marcone • 87 Rua Capitao Pedro Werlang • 159 Rua Capitao Pedro Werlang • 454 Avenida Elias Cirne Lima • 384 Avenida Elias Cirne Lima • 200 Avenida Elias Cirne Lima • 218 Rua Padre Todesco • 43 Rua Doutor Fernando Ortiz Schneider • Rua Doutor Felix Contreiras Rodrigues • 90 Rua Leopodo Machado Soares • 768 Rua Capitao Pedro Werlang • 1011 Rua Capitao Pedro Werlang • Rua Padre Todesco'
),
(
'C1','Circular Centro','Terminal Visconde Do Cairu/Terminal Mercado',
'Largo Visconde do Cairú • 90 Rua General Joao Manoel • 539 Rua 7 de Setembro • 388 Avenida Padre Tome • 385 Rua dos Andradas • 228 Rua General Salusitano • 330 Rua General Salustiano • 303 Rua General Vasco Alves • 366 Rua General Portinho • 690 Rua Duque De Caxias • 863 Rua Duque de Caxias • 973 Rua Duque de Caxias • 1304 Avenida Duque De Caxias • 1386 Rua Duque De Caxias • Rua Coronel Genuíno • Rua Antônio Klinger Filho • 1520 Avenida Loureiro Da Silva • SN Avenida Loureiro Da Silva • 1156 Rua Coronel Fernando Machado • 268 Rua Jeronimo Coelho • Rua Professor Annes Dias • Túnel da Conceição • Rua da Conceição • Avenida Júlio de Castilhos'
),
(
'C2','Circular Praça XV','Terminal Visconde Do Cairu/Terminal Mercado',
'Largo Visconde do Cairú • Rua General Bento Martins • 388 Avenida Padre Tome • 385 Rua dos Andradas • 228 Rua General Salusitano • 330 Rua General Salustiano • Rua Washington Luiz • 508 Rua General Vasco Alves • 474 Rua Washington Luiz • Rua Washington Luiz • 820 Rua Washington Luiz • 881 Rua Demétrio Ribeiro • 993 Avenida Borges De Medeiros • Rua Coronel Genuíno • Rua Antônio Klinger Filho • 26 Travessa do Carmo • 531 Rua José do Patrocínio • 824 Rua José do Patrocínio • 1009 Rua José do Patrocínio • SN Rua Jose Do Patrocinio • 1375 Avenida Joao Pessoa • 375 Rua Santana • Avenida Jerônimo de Ornelas • 1040 Avenida Venâncio Aires • Rua Felipe Camarão • 15 Rua Cabral • 25 Rua Coronel Frederico Linck • 750 Avenida Cristovao Colombo • 349 Avenida Cristovao Colombo • 374 Avenida Cristovao Colombo • 309 Avenida Farrapos • 789 Rua Voluntarios Da Patria • Avenida Júlio de Castilhos'
),
(
'C3','Circular Urca',' Terminal Borges De Medeiros/ Terminal Borges De Medeiros',
'Avenida Borges de Medeiros • 596 Avenida Julio De Castilhos • Rua da Conceição • 210 Rua Doutor Barros Cassal • 312 Rua Doutor Barros Cassal • 562 Avenida Independencia • Avenida Independência • Avenida Independência • SN Rua Fernandes Vieira • 286 Rua Fernandes Vieira • 449 Rua Fernandes Vieira • 753 Avenida José Bonifácio • Rua Ramiro Barcelos • 642 Avenida Jeronimo De Ornelas • Avenida Jerônimo de Ornelas • 216 Rua Santana • 489 Avenida Venancio Aires • Avenida Venâncio Aires • Avenida Venâncio Aires • Praça Garibaldi • 980 Avenida Aureliano De Figueiredo Pinto • Rua João Alfredo • 448 Rua João Alfredo • Avenida Loureiro da Silva • 1156 Rua Coronel Fernando Machado • 883 Rua Coronel Fernando Machado • 623 Rua Coronel Fernando Machado • 442 Rua Coronel Fernando Machado • 475 Rua General Bento Martins • 561 Rua General Cypriano Ferreira • 543 Rua General Portinho • 535 Rua General Vasco Alves • 24 Rua Washington Luiz • 303 Rua General Vasco Alves • 690 Rua Duque De Caxias • 863 Rua Duque de Caxias • 973 Rua Duque de Caxias • Largo João Amorim de Albuquerque • Rua Caldas Júnior • 1044 Rua Siqueira Campos • 1170 Rua Siqueira Campos • Avenida Borges de Medeiros'
),
(
'C4','Balada Segura',' Terminal Borges De Medeiros/ Terminal Mercado',
'Avenida Borges de Medeiros • Rua General Bento Martins • 437 Rua Siqueira Campos • 551 Avenida Presidente Joao Goulart • Ciclovia da Perimetral • Avenida Presidente João Goulart • SN Avenida Loureiro Da Silva • 26 Travessa do Carmo • 531 Rua José do Patrocínio • 824 Rua José do Patrocínio • 1009 Rua José do Patrocínio • SN Rua Jose Do Patrocinio • 1375 Avenida Joao Pessoa • 1244 Avenida Joao Pessoa • SN Avenida Joao Pessoa • 914 Avenida Osvaldo Aranha • 753 Avenida José Bonifácio • 266 Avenida Protasio Alves • Viaduto Tiradentes • 194 Rua Dona Eugenia • 194 Rua Dona Eugenia • 500 Rua Mariante • 38 Largo Dos Caixeiros Viajantes • Avenida Goethe • Rua Doutor Timóteo • 450 Rua Doutor Timoteo • 2506 Avenida Cristovao Colombo • 2696 Avenida Cristovao Colombo • 3025 Avenida Cristovao Colombo • 3111 Avenida Cristovao Colombo • 1351 Rua Dom Pedro II • 145 Avenida Augusto Meyer • 372 Avenida Plinio Brasil Milano • 126 Avenida Plinio Brasil Milano • 1744 Rua 24 De Outubro • 1644 Rua 24 De Outubro • 1466 Rua 24 De Outubro • 1208 Rua 24 De Outubro • 577 Rua Quintino Bocaiuva • 805 Avenida 24 de Outubro • 700 Rua 24 De Outubro • 408 Rua 24 De Outubro • 200 Rua 24 De Outubro • 111 Rua 24 de Outubro • 1081 Rua Ramiro Barcelos • 936 Avenida Independência • 769 Avenida Independência • 960 Rua Garibaldi • 429 Avenida Independencia • 275 Avenida Independência • 498 Rua Pinto Bandeira • 410 Avenida Alberto Bins • Avenida Júlio de Castilhos'
),
(
'D43','Universitária','Campus Ufrgs/Terminal Borges De Medeiros',
'9090 Avenida Bento Gonçalves • Avenida Bento Gonçalves • 7500 Beco Dos Marianos • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • Avenida Ipiranga • 4952 Avenida Ipiranga • 1342 Rua Santa Cecilia • Rua João Guimarães • Avenida Protásio Alves • 140 Avenida Protasio Alves • 1208 Avenida Osvaldo Aranha • 824 Avenida Osvaldo Aranha • 444 Avenida Osvaldo Aranha • Rua da Conceição • Avenida Borges de Medeiros'
),
(
'T1','Triângulo/Receita Federal','Terminal Triângulo/Receita Federal',
'4320 Avenida Assis Brasil • 3522 Avenida Assis Brasil • 2883 Avenida Assis Brasil • 65 Rua Itarare • Avenida Assis Brasil • 222 Rua Jary • 600 Avenida Grecia • 868 Avenida Grecia • 318 Avenida Joao Wallig • 479 Avenida Joao Wallig • 635 Avenida Joao Wallig • 840 Avenida Joao Wallig • 1795 Avenida João Wallig • 2151 Avenida Joao Wallig • 27 Rua Desembargador Hugo Candal • 831 Avenida Teixeira Mendes • 546 Avenida Teixeira Mendes • 390 Avenida Teixeira Mendes • 148 Avenida Teixeira Mendes • SN Avenida Jordao • 639 Rua Jerusalem • 609 Rua Sao Benedito • 1010 Rua Sao Benedito • 330 Rua Professor Pedro Santa Helena • 140 BLOCO A Rua Professor Pedro Santa Helena • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • 331 Rua Jacob Vontobel • Avenida Ipiranga • 4952 Avenida Ipiranga • 15 Rua Alcebiades Caetano Da Silva • 4000 Avenida Ipiranga • 3740 Avenida Ipiranga • Avenida Ipiranga • 1342 Rua Santa Cecilia • 465 Rua Joao Guimaraes • 2752 Avenida Ipiranga • 2000 Avenida Ipiranga • 3 Rua Delegado Grant • 1801 Rua General Lima E Silva • Avenida Ipiranga • 810 Rua Dezessete De Junho • 387 Rua Dezessete De Junho • Avenida Praia de Belas • Avenida Aureliano de Figueiredo Pinto • 80 Avenida Aureliano de Figueiredo Pinto • SN Avenida Augusto De Carvalho • Avenida Presidente João Goulart'
),
(
'T10','Triângulo/Campus do Vale','Terminal Triângulo/Terminal Campus Ufrgs',
'Avenida Assis Brasil • Avenida Baltazar de Oliveira Garcia • 1502 Avenida Baltazar De Oliveira Garcia • 91 Avenida Manoel Elias • SN Avenida Manoel Elias • 900 Avenida Manoel Elias • 1116 Avenida Manoel Elias • 2001 Avenida Manoel Elias • 142 Acesso M • 42 Acesso A • 8423 Avenida Protasio Alves • 8059 Avenida Protasio Alves • Avenida Nilo Ruschel • 7600 Avenida Protásio Alves • 2265 Avenida Antonio De Carvalho • Avenida Antônio de Carvalho • 2130 Avenida Antonio De Carvalho • 1660 Avenida Antonio De Carvalho • 1471 Avenida Antonio De Carvalho • Rua Comendador Eduardo Secco • 331 Avenida Antônio de Carvalho • 6881 Avenida Bento Gonçalves • Beco Quatro • 7712 Avenida Bento Goncalves • Avenida Bento Gonçalves'
),
(
'T11','Aeroporto/3ª Perimetral','Terminal Denize Crespo Gay Da Fonseca/Aeroporto Desembarque',
'Rua Denize Crespo Gay da Fonseca • 1151 Avenida Juca Batista • 484 Avenida Juca Batista • 330 Avenida Juca Batista • 6347 Avenida Cavalhada • 5793 Avenida Cavalhada • 5516 Avenida Cavalhada • 5250 Avenida Cavalhada • 4760 Avenida Cavalhada • 4551 Avenida Cavalhada • 3783 Avenida Cavalhada • 3621 Avenida da Cavalhada • 3204 Beco 3 • Avenida da Cavalhada • 2360 Avenida Cavalhada • Avenida da Cavalhada • 1860 Avenida Cavalhada • 1517 Avenida Nonoai • 303 Avenida Nonoai • Avenida Nonoai • 238 Avenida Nonoai • 35 Rua Costa Lima • 3171 Avenida Teresopolis • Avenida Teresópolis • Avenida David Jozef Kapel • 452 Avenida Coronel Aparicio Borges • Avenida Coronel Aparício Borges • 1312 Avenida Coronel Aparicio Borges • 83 Rua Sao Miguel • 2199 Avenida Coronel Aparicio Borges • 2730 Avenida Coronel Aparício Borges • 1140 Rua Doutor Salvador Franca • 12 Rua Engenheiro Antonio Carlos Tibirica • 442 Avenida Senador Tarso Dutra • SN Avenida Protasio Alves • SN Avenida Carlos Gomes • 555 Avenida Soledade • Viaduto Jayme Caetano Braun • 350 Avenida Carlos Gomes • 146 Avenida Augusto Meyer • 3452 Avenida Cristovao Colombo • 728 Rua Dom Pedro Ii • 390 Rua Dom Pedro II • Viaduto José Eduardo Utzig • 283 Rua Souza Reis • 517 Rua Souza Reis • 468 Rua Edu Chaves • Rua Edú Chaves'
),
(
'T11A','3ª Perimetral/Ant. Carvalho','Terminal Antônio De Carvalho/Terminal Antônio De Carvalho',
'861 Rua Doutor Telmo Vergara • SN Avenida Elias Cirne Lima • 5153 Avenida Bento Goncalves • 46 Rua Frei Germano • 4592 Avenida Bento Goncalves • Rua General Telmo de Oliveira Santana • 3614 Avenida Bento Goncalves • 177 Avenida Silvado • 318 Rua Silvado • 451 Rua Silvado • 2730 Avenida Coronel Aparício Borges • 1140 Rua Doutor Salvador Franca • 12 Rua Engenheiro Antonio Carlos Tibirica • 442 Avenida Senador Tarso Dutra • SN Avenida Protasio Alves • SN Avenida Carlos Gomes • 555 Avenida Soledade • Viaduto Jayme Caetano Braun • 350 Avenida Carlos Gomes • 146 Avenida Augusto Meyer • 3452 Avenida Cristovao Colombo • 728 Rua Dom Pedro Ii • 390 Rua Dom Pedro II • Rua Dom Pedro II • 367 Rua Dom Pedro II • 728 Rua Dom Pedro Ii • 1103 Rua Dom Pedro Ii • Avenida Plínio Brasil Milano • Avenida Carlos Gomes • Viaduto Jayme Caetano Braun • 555 Avenida Soledade • 1723 Avenida Carlos Gomes • Avenida Protásio Alves • Rua Doutor José Carvalho Bernardes • 1115 Rua Doutor Salvador Franca • 667 Rua Doutor Salvador Franca • Viaduto São Jorge • SN Beco Um • 2873 Avenida Bento Gonçalves • 4301 Avenida Bento Gonçalves • 4714 Avenida Bento Goncalves • 10 Rua Primeiro de Setembro • SN Avenida Elias Cirne Lima • 6122 Avenida Bento Goncalves'
),
(
'T12','Restinga/Cairú','Terminal Nilo Wulff/Terminal Cairú',
'SN Acesso A Sq5 • 939 Avenida Economista Nilo Wulff • Avenida Economista Nilo Wulff • Acesso K • 2230 Alameda V Sq5 • 4 Rua C • Beco 7 • 2920 C Estrada J A S • 26 Acesso 7154 • Rua Padre Pedro Leonardi • Rua Sete Mil Cento e Quarenta e Seis • 17 Rua Pedro Leonardi • 105 Rua Valter De Azeredo • Estrada João de Oliveira Remião • 161 Rua Zeppelin • 6791 Estrada João de Oliveira Remião • 6638 Estrada João de Oliveira Remião • 6349 Estrada Joao De Oliveira Remiao • 5840 Estrada Joao De Oliveira Remiao • 5512 Estrada Joao De Oliveira Remiao • 5559 Estrada Joao De Oliveira Remiao • 5120 Estrada João de Oliveira Remião • 4520 Estrada Joao De Oliveira Remiao • 5012 Estrada João de Oliveira Remião • 4425 Estrada Joao De Oliveira Remiao • 3626 Rua Joao De Oliveira Remiao • 2725 Avenida Joao De Oliveira Remiao • 1787 Entrada Joao De Oliveira Remiao • 790 Avenida Joao De Oliveira Remiao • Avenida Bento Gonçalves • 7500 Beco Dos Marianos • 861 Rua Doutor Telmo Vergara • SN Avenida Elias Cirne Lima • 5153 Avenida Bento Goncalves • 75 Rua Frei Germano • 205 Rua Frei Germano • 275 Avenida Frei Germano • 7110 FUNDOS Rua Sao Marino • 331 Rua Jacob Vontobel • 751 Rua Doutor Salvador Franca • 12 Rua Engenheiro Antonio Carlos Tibirica • 442 Avenida Senador Tarso Dutra • SN Avenida Protasio Alves • SN Avenida Carlos Gomes • 555 Avenida Soledade • Viaduto Jayme Caetano Braun • 350 Avenida Carlos Gomes • 146 Avenida Augusto Meyer • 3452 Avenida Cristovao Colombo • 728 Rua Dom Pedro Ii • 390 Rua Dom Pedro II • Viaduto José Eduardo Utzig • Rua Doutor João Inácio • 1008 Avenida Ceara • 320 Avenida Amazonas • 763 Rua Cairu'
),
(
'T12.1','Pitinga/Cairú','Armando Pedro Da Rosa/Terminal Cairú',
'54 Rua Portal Da Figueira • Estrada João de Oliveira Remião • 161 Rua Zeppelin • 6791 Estrada João de Oliveira Remião • 6638 Estrada João de Oliveira Remião • 6349 Estrada Joao De Oliveira Remiao • 5840 Estrada Joao De Oliveira Remiao • 5512 Estrada Joao De Oliveira Remiao • 5559 Estrada Joao De Oliveira Remiao • 5120 Estrada João de Oliveira Remião • 4520 Estrada Joao De Oliveira Remiao • 5012 Estrada João de Oliveira Remião • 4425 Estrada Joao De Oliveira Remiao • 3626 Rua Joao De Oliveira Remiao • 2725 Avenida Joao De Oliveira Remiao • 1787 Entrada Joao De Oliveira Remiao • 790 Avenida Joao De Oliveira Remiao • Avenida Bento Gonçalves • 7500 Beco Dos Marianos • 861 Rua Doutor Telmo Vergara • SN Avenida Elias Cirne Lima • 5153 Avenida Bento Goncalves • 75 Rua Frei Germano • 205 Rua Frei Germano • 275 Avenida Frei Germano • 7110 FUNDOS Rua Sao Marino • 331 Rua Jacob Vontobel • 751 Rua Doutor Salvador Franca • 12 Rua Engenheiro Antonio Carlos Tibirica • 442 Avenida Senador Tarso Dutra • SN Avenida Protasio Alves • SN Avenida Carlos Gomes • 555 Avenida Soledade • Viaduto Jayme Caetano Braun • 350 Avenida Carlos Gomes • 146 Avenida Augusto Meyer • 3452 Avenida Cristovao Colombo • 728 Rua Dom Pedro Ii • 390 Rua Dom Pedro II • Viaduto José Eduardo Utzig • Rua Doutor João Inácio • 1008 Avenida Ceara • 320 Avenida Amazonas • 763 Rua Cairu'
),
(
'T12A','Restinga/PUC','Terminal Nilo Wulff/Cubanos',
'SN Acesso A Sq5 • 939 Avenida Economista Nilo Wulff • Avenida Economista Nilo Wulff • Acesso K • 2230 Alameda V Sq5 • 4 Rua C • Beco 7 • 2920 C Estrada J A S • 26 Acesso 7154 • Rua Padre Pedro Leonardi • Rua Sete Mil Cento e Quarenta e Seis • 17 Rua Pedro Leonardi • 105 Rua Valter De Azeredo • Estrada João de Oliveira Remião • 161 Rua Zeppelin • 6791 Estrada João de Oliveira Remião • 6638 Estrada João de Oliveira Remião • 6349 Estrada Joao De Oliveira Remiao • 5840 Estrada Joao De Oliveira Remiao • 5512 Estrada Joao De Oliveira Remiao • 5559 Estrada Joao De Oliveira Remiao • 5120 Estrada João de Oliveira Remião • 4520 Estrada Joao De Oliveira Remiao • 5012 Estrada João de Oliveira Remião • 4425 Estrada Joao De Oliveira Remiao • 3626 Rua Joao De Oliveira Remiao • 2725 Avenida Joao De Oliveira Remiao • 1787 Entrada Joao De Oliveira Remiao • 790 Avenida Joao De Oliveira Remiao • Avenida Bento Gonçalves • 7500 Beco Dos Marianos • 861 Rua Doutor Telmo Vergara • SN Avenida Elias Cirne Lima • 5153 Avenida Bento Goncalves • 46 Rua Frei Germano • 4592 Avenida Bento Goncalves • Rua General Telmo de Oliveira Santana • 1267 Rua Guilherme Alves • 1400 Rua Guilherme Alves • 1023 Rua Guilherme Alves • 5200 Avenida Ipiranga • Rua Doutor Salvador França • 6113 Avenida Ipiranga • 6311 Avenida Ipiranga • 5800 Avenida Ipiranga • Avenida dos Cubanos • 346 Rua Albion'
),
(
'T13','Triângulo/PUC','Terminal Triângulo/Cubanos',
'4320 Avenida Assis Brasil • 3522 Avenida Assis Brasil • 2883 Avenida Assis Brasil • 65 Rua Itarare • Avenida Assis Brasil • Avenida Plínio Brasil Milano • 2322 Avenida Plinio Brasil Milano • Avenida Plínio Brasil Milano • Avenida Plínio Brasil Milano • 497 Rua Veranopolis • Avenida Plínio Brasil Milano • 4308 Rua Cristovao Colombo • 1000 Avenida Plinio Brasil Milano • 935 Avenida Plinio Brasil Milano • 840 Praca Alberto Ramos • Avenida Plínio Brasil Milano • Avenida Carlos Gomes • Viaduto Jayme Caetano Braun • 555 Avenida Soledade • 1723 Avenida Carlos Gomes • Avenida Protásio Alves • Rua Doutor José Carvalho Bernardes • 1115 Rua Doutor Salvador Franca • 667 Rua Doutor Salvador Franca • 6113 Avenida Ipiranga • 6311 Avenida Ipiranga • 5800 Avenida Ipiranga • Avenida dos Cubanos • 346 Rua Albion'
),
(
'T1D','Linha Direta - Triângulo/Receita Federal','Terminal Triângulo/Receita Federal',
'4320 Avenida Assis Brasil • 3522 Avenida Assis Brasil • 2883 Avenida Assis Brasil • 65 Rua Itarare • Avenida Assis Brasil • 318 Avenida Joao Wallig • 1795 Avenida João Wallig • 1010 Rua Sao Benedito • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • Avenida Ipiranga • 4952 Avenida Ipiranga • 1342 Rua Santa Cecilia • 2752 Avenida Ipiranga • 3 Rua Delegado Grant • Avenida Ipiranga • 810 Rua Dezessete De Junho • 387 Rua Dezessete De Junho • Avenida Aureliano de Figueiredo Pinto • Avenida Presidente João Goulart'
),
(
'T2','Est. Farrapos/Praia de Belas','Terminal Peri Machado/Estação Farrapos',
'Rua Pery Machado • 3120 Avenida Borges de Medeiros • Rua José de Alencar • 537 Rua José de Alencar • 203 Rua Doutor Oscar Bittencourt • 940 Rua José de Alencar • 165 Rua Paes De Andrade • Avenida Coronel Gastão Hasslocher Mazeron • 65 Avenida Coronel Gastao Haslocher Mazeron • Avenida Oswaldo Rolla • 1000 Avenida Doutor Carlos Barbosa • 117 Rua General Gomes Carneiro • 120 Travessa Alfredo Costa • 612 Rua Coronel Neves • Avenida Professor Oscar Pereira • 2411 Avenida Professor Oscar Pereira • 513 Avenida Coronel Aparicio Borges • Avenida Coronel Aparício Borges • 1312 Avenida Coronel Aparicio Borges • 83 Rua Sao Miguel • 2199 Avenida Coronel Aparicio Borges • 2730 Avenida Coronel Aparício Borges • 751 Rua Doutor Salvador Franca • 1115 Rua Doutor Salvador Franca • 1707 Rua Doutor Salvador França • 442 Avenida Senador Tarso Dutra • 315 Rua Joao Caetano • 555 Avenida Soledade • 88 Alameda Alceu Wamosy • 350 Avenida Carlos Gomes • 737 Avenida Plinio Brasil Milano • 1805 Rua Honório Silveira Dias • 1053 Rua Luzitana • 910 Rua Luzitana • 165 Avenida Benjamin Constant • Viaduto José Eduardo Utzig • 320 Avenida Amazonas • 900 Rua Cairu • 1202 Avenida Pernambuco • 1048 Avenida Pernambuco • 640 Avenida Pernanbuco • SN Rua Professor Sarmento Barata • 4211 Avenida Farrapos'
),
(
'T2A','Farrapos / P. Belas via Paulino Azurenha','Terminal Peri Machado/Padre Leopoldo Brentano',
'Rua Pery Machado • 3120 Avenida Borges de Medeiros • Rua José de Alencar • 537 Rua José de Alencar • 203 Rua Doutor Oscar Bittencourt • 940 Rua José de Alencar • 165 Rua Paes De Andrade • Avenida Coronel Gastão Hasslocher Mazeron • 65 Avenida Coronel Gastao Haslocher Mazeron • Avenida Oswaldo Rolla • 1000 Avenida Doutor Carlos Barbosa • 117 Rua General Gomes Carneiro • 120 Travessa Alfredo Costa • 612 Rua Coronel Neves • Avenida Professor Oscar Pereira • 2411 Avenida Professor Oscar Pereira • 513 Avenida Coronel Aparicio Borges • Avenida Coronel Aparício Borges • 1312 Avenida Coronel Aparicio Borges • 83 Rua Sao Miguel • 2199 Avenida Coronel Aparicio Borges • 2730 Avenida Coronel Aparício Borges • 751 Rua Doutor Salvador Franca • 1115 Rua Doutor Salvador Franca • 1707 Rua Doutor Salvador França • 442 Avenida Senador Tarso Dutra • 315 Rua Joao Caetano • 555 Avenida Soledade • 88 Alameda Alceu Wamosy • 350 Avenida Carlos Gomes • 737 Avenida Plinio Brasil Milano • 1805 Rua Honório Silveira Dias • 1053 Rua Luzitana • 910 Rua Luzitana • 165 Avenida Benjamin Constant • Viaduto José Eduardo Utzig • 320 Avenida Amazonas • 900 Rua Cairu • 1202 Avenida Pernambuco • 1048 Avenida Pernambuco • 640 Avenida Pernanbuco • SN Rua Professor Sarmento Barata • 4211 Avenida Farrapos'
),
(
'T3','Est. São Pedro / Barra Shopping',' Estação São Pedro/Diário De Notícias - Barra Shopping Sul',
'160 Avenida Polonia • 272 Rua Ernesto Fontoura • 270 Avenida Rio Grande • 404 Avenida Brasil • 687 Avenida Presidente Franklin Roosevelt • Avenida Presidente Franklin Roosevelt • 1105 Avenida Presidente Franklin Roosevelt • 1406 Avenida Presidente Franklin Roosevelt • 885 Rua Almirante Tamandare • 486 Rua Felix Da Cunha • 697 Rua Félix da Cunha • 1078 Rua Felix Da Cunha • 750 Rua 24 de Outubro • Avenida Goethe • 19 Avenida Goethe • 290 Avenida Goethe • Rua Mariante • Travessa Helena Speroto • 194 Rua Dona Eugenia • 2752 Avenida Ipiranga • 993 Rua Santana • Rua Santana • 1475 Rua Santana • 596 Avenida Bento Goncalves • 811 Avenida Bento Goncalves • 997 Avenida Bento Goncalves • 151 Rua Luiz De Camoes • 178 Rua Paulino Chaves • 9 Rua Padre Antonio Vieira • 60 Rua Doutor Malheiros • 1532 Rua Professor Oscar Pereira • Avenida Professor Oscar Pereira • 30 Rua Aguas Mortas • 612 Rua Coronel Neves • 360 Avenida Niteroi • 120 Avenida Niteroi • 47 Beco 1 • SN Rua Gabriel Fialho Camargo • 151 Rua Manoel Lobato • 501 Beco 27 • 23 Avenida Moab Caldas • 37 Acesso 65 • 1459 Rua Cruzeiro Do Sul • 1945 Rua Cruzeiro Do Sul • 1791 Rua Cruzeiro Do Sul • Rua Cruzeiro do Sul • 2436 Rua Cruzeiro Do Sul • 2461 Avenida Da Divisa • 238 Rua Arapei • 183 Rua Comandai • 470 Rua Butui • 291 Rua Jatai • 58 Rua Butui • SN Avenida Icarai • Avenida Icaraí • 11 Avenida Icarai • 1719 Avenida Icaraí • Avenida Icaraí • Avenida Diário de Notícias • Ciclovia Eduardo d Gord Schaan • 915 Avenida Diário de Notícias'
),
(
'T4','Triângulo/Barra Shopping',' Terminal Triângulo/Diário De Notícias - Barra Shopping Sul',
'Avenida Assis Brasil • 3522 Avenida Assis Brasil • 323 Rua Alianca • 230 Rua Amoroso Costa • 71 Avenida Bernardi • 3226 Avenida Assis Brasil • 290 Rua Dom Diogo De Souza • 530 Rua Dom Diogo De Souza • 135 Rua Limoeiro • 851 Avenida Do Forte • 1129 Avenida Do Forte • 1278 Avenida Do Forte • 1551 Avenida Do Forte • 1593 Avenida Saturnino De Brito • Avenida Saturnino de Brito • 1167 Avenida Saturnino De Brito • 1112 Avenida Saturnino De Brito • 675 Avenida Saturnino De Brito • 467 Rua General Salvador Pinheiro • 355 Avenida Saturnino De Brito • 33 Rua Sao Gabriel • 5852 Avenida Protasio Alves • 6180 Avenida Protasio Alves • 6220 Avenida Protasio Alves • 6565 Avenida Protásio Alves • 2265 Avenida Antonio De Carvalho • Avenida Antônio de Carvalho • 2130 Avenida Antonio De Carvalho • 1660 Avenida Antonio De Carvalho • 1471 Avenida Antonio De Carvalho • Rua Comendador Eduardo Secco • 331 Avenida Antônio de Carvalho • Avenida Ipiranga • 8450 Avenida Ipiranga • 8400 TORRE 7 Avenida Ipiranga • 8550 Avenida Ipiranga • 7110 FUNDOS Rua Sao Marino • Passarela da Pontifícia Universidade Católica do Rio Grande do Sul • 331 Rua Jacob Vontobel • Viaduto São Jorge • 2260 Avenida Coronel Aparicio Borges • Avenida Coronel Aparício Borges • SN Avenida Coronel Aparicio Borges • 1312 Avenida Coronel Aparicio Borges • Avenida Coronel Aparício Borges • 452 Avenida Coronel Aparicio Borges • Avenida David Jozef Kapel • Avenida Teresópolis • Avenida Teresópolis • 69 Avenida Nonoai • 255 Avenida Nonoai • 629 Avenida Nonoai • 1195 Avenida Nonoai • 303 Avenida Nonoai • 1517 Avenida Nonoai • Rua Doutor Campos Velho • 1526 Rua Doutor Campos Velho • 1210 Rua A • 1158 Rua Jaguari • Rua Doutor Campos Velho • 11 Avenida Icarai • 1719 Avenida Icaraí • Avenida Icaraí • Avenida Diário de Notícias • Ciclovia Eduardo d Gord Schaan • 915 Avenida Diário de Notícias'
);
